export const SET_LOGIN_STATE: string = "SET_LOGIN_STATE";
export const SET_APP_READY_STATE: string = "SET_APP_READY_STATE";
export const SET_USER_DATA: string = "SET_USER_DATA";

export const SET_SELECTED_NUMBER: string = "SET_SELECTED_NUMBER";
export const GET_NUMBER_INFO_FETCH_STATE: string = "GET_NUMBER_INFO_FETCH_STATE";

export const SET_NUMBERS_LIST: string = "SET_NUMBERS_LIST";
export const SET_NUMBERS_LIST_PAGE: string = "SET_NUMBERS_LIST_PAGE";
export const SET_NUMBERS_LIST_BUSY_STATE: string = "SET_NUMBERS_LIST_BUSY_STATE";
export const SET_NUMBERS_LIST_LENGTH: string = "SET_NUMBERS_LIST_LENGTH";
export const SET_NUMBERS_STATUSES: string = "SET_NUMBERS_STATUSES";
export const SET_NUMBERS_SORTING_STATE: string = "SET_NUMBERS_SORTING_STATE";
export const SET_NUMBERS_TARIFFS: string = "SET_NUMBERS_TARIFFS";
export const SET_NUMBERS_GROUP: string = "SET_NUMBERS_GROUP";
export const TOGGLE_NUMBERS_FILTER: string = "TOGGLE_NUMBERS_FILTER";
export const SET_NUMBERS_DEALERS: string = "SET_NUMBERS_DEALERS";

export const SET_DETAIL_RESULT: string = "SET_DETAIL_RESULT";
export const SET_DETAIL_ERROR: string = "SET_DETAIL_ERROR";
export const SET_DETAIL_FETCHING_STATE: string = "SET_DETAIL_FETCHING_STATE";

export const SET_FETCH_ACTIVATIONS_STATE: string = "SET_FETCH_ACTIVATIONS_STATE";
export const SET_FETCH_ACTIVATIONS_ERROR: string = "SET_FETCH_ACTIVATIONS_ERROR";
export const SET_FETCH_ACTIVATIONS_RESULT: string = "SET_FETCH_ACTIVATIONS_RESULT";
export const TOGGLE_ACTIVATIONS_FILTER: string = "TOGGLE_ACTIVATIONS_FILTER";
export const SET_ACTIVATIONS_PAGE: string = "SET_ACTIVATIONS_PAGE";

export const SET_SEARCH_STRING: string = "SET_SEARCH_STRING";
export const SET_SEARCH_MODE: string = "SET_SEARCH_MODE";

export const SET_USERS_LIST: string = "SET_USERS_LIST";
export const SET_USERS_FETCHING_STATE: string = "SET_USERS_FETCHING_STATE";
export const SET_USERS_FETCHING_ERROR_STATE: string = "SET_USERS_FETCHING_ERROR_STATE";
export const SET_DEALERS_LIST: string = "SET_DEALERS_LIST";

export const TOGGLE_THEME: string = "TOGGLE_THEME";
